package main

import (
	"errors"
	"fmt"
	"math/rand"
)

func CallBackCatch(cfg *config, args ...string) error {

	if len(args) != 1 {
		return errors.New("Pokemon not found in this area 0_o")
	}
	pokemonName := args[0]

	pokemon_data, err := cfg.pokeapiClient.GetPokemon(pokemonName)
	if err != nil {
		return err
	}

	const threshold = 50
	randNum := rand.Intn(pokemon_data.BaseExperience)
	if randNum < threshold {
		return fmt.Errorf("FAILED TO CATCH %s", pokemonName)
	}
	fmt.Printf("%s WAS CAPTURED >_< \n", pokemonName)
	cfg.caughtPokemon[pokemonName] = pokemon_data
	return nil
}

func CallBackInspect(cfg *config, args ...string) error {

	if len(args) != 1 {
		return errors.New("Pokemon not found in this area 0_o")
	}
	pokemonName := args[0]

	pokemon_data, err := cfg.pokeapiClient.GetPokemon(pokemonName)
	if err != nil {
		return err
	}

	const threshold = 50
	randNum := rand.Intn(pokemon_data.BaseExperience)
	if randNum < threshold {
		return fmt.Errorf("FAILED TO CATCH %s", pokemonName)
	}
	fmt.Printf("%s WAS CAPTURED >_< \n", pokemonName)
	cfg.caughtPokemon[pokemonName] = pokemon_data
	return nil
}
